Add source of truth prop
janosh/svelte-multiselect pull request #73
Opened 2022-04-17 13:03 UTC by GodPingu

This pull resolves #22 by adding a sourceOfTruth prop which is used by the multiselect component to determine which selected prop to respond to changes on. I also renamed selected to selectedOptions for clarity in relation to the SourceOfTruth enum.

This pull request includes a new prop, a new enum, a new example, as well as changing the name of "selected" to "selectedOptions"

2022-04-17 15:44 UTC, janosh requested changes

2022-04-17 15:44 UTC, janosh commented on src/lib/MultiSelect.svelte
> +  switch (sourceOfTruth) {
Not a huge fan of switch cases tbh as I find them less readable and more verbose. Could we swap this for `if`/`else if`/...?

2022-04-17 15:44 UTC, janosh commented on src/lib/index.ts
> +export enum SourceOfTruth {
I think it's safe enough to type-hint the `sourceOfTruth` prop as `'options' | 'labels' | 'values'`. No need to use a enum here I think. TS will complain any way if we make a non-sensical comparison like ``case `foobar`:``.

2022-04-17 15:45 UTC, janosh commented
@GodPingu Thanks for the contribution! Could you document the new `sourceOfTruth` prop in the readme and fix the other failing test? I also left some comments.

2022-04-17 16:33 UTC, GodPingu commented on src/lib/index.ts
> +export enum SourceOfTruth {
Agree about this I've just switched it to a type over an enum

2022-04-17 16:41 UTC, GodPingu commented on src/lib/MultiSelect.svelte
> +  switch (sourceOfTruth) {
Swapped these over

2022-04-17 18:54 UTC, GodPingu commented
Believe I've fixed the test and completed any changes you wanted

2022-04-18 10:52 UTC, closed without merging

2022-04-18 10:53 UTC, janosh commented
Thanks for the getting the ball rolling. After giving it some more thought, the easiest solution actually seems to not force options to be objects internally but rather to work with whatever the user passes in. If we get strings or numbers, just leave them as strings/numbers. I wasn't sure how well that would work but after giving it a try locally, seems like it requires much less code and is more readable. It still doesn't allow controlling the selected options with two-way binding via `selectedLabels` and `selectedValues` but those were mostly added for people who didn't want to deal with options objects if they supplied simple strings. Now that this restriction is lifted, I think it is fine to mark `selectedLabels` and `selectedValues` as read-only since bind:selected can now be used to control options externally in the same shape as they were provided.

I'll push my changes here and then merge your PR so your work is credited.

2022-04-18 10:54 UTC, janosh commented
Oops, I messed this up. Accidentally force pushed to your fork. Very sorry! Could you open another PR?

2022-04-18 11:04 UTC, GodPingu commented
Just created a new pull request thanks

2022-04-18 11:17 UTC, GodPingu commented
Having given thought to it I think this makes sense it was getting quite verbose trying to deal with values/labels etc. I think the use of slot components where users need the difference between values and labels/display info, as already implemented, is the best solution